const API_ROUTES = {
    SEARCH_CARD: '/Card/SearchCard',
    GET_TYPE: '/Card/GetCardType',
    GET_ORIGIN: '/Card/GetCardOrigin',
    GET_ELEMENT: '/Card/GetCardElement',
    GET_RARITY: '/Card/GetCardRarity',
    SEARCH_DEAL: '/Deal/SearchDeal',
    GET_BOUGHT_DEAL: '/Deal/GetBoughtDeal',
    GET_SOLD_DEAL: '/Deal/GetSoldDeal',
    CREATE_DEAL: '/Deal/CreateDeal',
    EDIT_DEAL: '/Deal/EditDeal',
    DELETE_DEAL: '/Deal/DeleteDeal',
    ACCEPT_DEAL: '/Deal/AcceptDeal',
    GACHA: '/Gacha',
    REGISTER: '/User/Register',
    LOGIN: '/User/Login',
    FORGET_PASSWORD: '/User/ForgetPassword',
    CHANGE_PASSWROD: '/User/ChangePassword',
    CHANGE_EMAIL: '/User/ChangeEmail',
    CHANGE_AVATAR: '/User/ChangeAvatarUrl',
    USERCARD_SEARCH_OWNED_SEPARATE: '/UserCard/SearchOwnedSeparate',
    USERCARD_SEARCH_OWNED_STACK: '/UserCard/SearchOwnedStack',
    GET_INFO: '/User/GetInfo',
}

export default API_ROUTES